/*
 * LoginView.java
 *
 * Created on __DATE__, __TIME__
 */

package View;

import java.awt.HeadlessException;
import java.io.IOException;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import model.Admin;
import model.Shop;
import model.User;
import model.client;

/**
 *
 * @author  __USER__
 */
public class LoginView extends javax.swing.JFrame {

	/** Creates new form LoginView */
	public LoginView() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton3 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jButton4 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jRadioButton1 = new javax.swing.JRadioButton();
		jRadioButton2 = new javax.swing.JRadioButton();
		jRadioButton3 = new javax.swing.JRadioButton();
		jPasswordField1 = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setUndecorated(true);

		jPanel1.setBackground(new java.awt.Color(236, 227, 228));

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel1.setText(" \u8d26\u53f7:");

		jButton3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton3.setText("\u767b\u5f55");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton3ActionPerformed(evt);
				} catch (HeadlessException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel3.setText("\u6ca1\u6709\u8d26\u53f7\uff1f");

		jButton4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton4.setText("\u6ce8\u518c");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jPanel3.setBackground(new java.awt.Color(236, 227, 228));

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36));
		jLabel4.setForeground(new java.awt.Color(204, 204, 255));
		jLabel4.setText("\u767b\u5f55");

		jButton1.setText("X");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel3Layout.createSequentialGroup().addContainerGap(185,
						Short.MAX_VALUE).addComponent(jLabel4).addGap(152, 152,
						152).addComponent(jButton1)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(jLabel4))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel2.setText(" \u5bc6\u7801:");

		jRadioButton1.setBackground(new java.awt.Color(236, 227, 228));
		buttonGroup1.add(jRadioButton1);
		jRadioButton1.setText("\u7528\u6237");

		jRadioButton2.setBackground(new java.awt.Color(236, 227, 228));
		buttonGroup1.add(jRadioButton2);
		jRadioButton2.setText("\u5e97\u94fa");

		jRadioButton3.setBackground(new java.awt.Color(236, 227, 228));
		buttonGroup1.add(jRadioButton3);
		jRadioButton3.setText("\u7ba1\u7406\u5458");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(49, 49, 49)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel2)
														.addComponent(jLabel1))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPasswordField1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																323,
																Short.MAX_VALUE)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																323,
																Short.MAX_VALUE))
										.addContainerGap())
						.addComponent(jPanel3,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(58, 58, 58)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton4))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jRadioButton1)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jRadioButton2)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jRadioButton3))
														.addComponent(
																jButton3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																324,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(68, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(
												jPanel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(96, 96, 96)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																39,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																jPasswordField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																34,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(84, 84, 84)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jRadioButton1)
														.addComponent(
																jRadioButton2)
														.addComponent(
																jRadioButton3))
										.addGap(74, 74, 74)
										.addComponent(jButton3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(jButton4))
										.addContainerGap(163, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new RegisterView().setVisible(true);
		this.dispose();
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)
			throws HeadlessException, ClassNotFoundException {
		//		String id = this.jTextField1.getText();
		//		String pw = this.jPasswordField1.getText();
		//		if (this.jRadioButton1.isSelected()) {
		//			User u = new User();
		//			try {
		//				if (u.login(id, pw)) {
		//					new UserMainView(id).setVisible(true);
		//					this.dispose();
		//				} else {
		//					JOptionPane.showMessageDialog(this, "登陆失败");
		//				}
		//			} catch (SQLException e) {
		//				e.printStackTrace();
		//				JOptionPane.showMessageDialog(this, "登陆失败");
		//			}
		//
		//		} else if (this.jRadioButton2.isSelected()) {
		//			Shop t = new Shop();
		//			try {
		//				if (t.login(id, pw)) {
		//					new ShopMainView(id).setVisible(true);
		//					this.dispose();
		//				} else {
		//					JOptionPane.showMessageDialog(this, "登陆失败");
		//				}
		//			} catch (SQLException e) {
		//				e.printStackTrace();
		//				JOptionPane.showMessageDialog(this, "登陆失败");
		//			}
		//		} else if (this.jRadioButton3.isSelected()) {
		//			Admin f = new Admin();
		//			try {
		//				if (f.login(id, pw)) {
		//					new AdminMainView().setVisible(true);
		//					this.dispose();
		//				} else {
		//					JOptionPane.showMessageDialog(this, "登陆失败");
		//				}
		//			} catch (SQLException e) {
		//				e.printStackTrace();
		//				JOptionPane.showMessageDialog(this, "登陆失败");
		//			}
		//		} else {
		//			JOptionPane.showMessageDialog(this, "请选择身份");
		//		}
		try {
			String num;
			client c = new client();
			String name = this.jTextField1.getText();
			String pw = this.jPasswordField1.getText();
			if (this.jRadioButton1.isSelected()) {

				boolean b = c.login(name, pw, 1);
				if (b) {
					JOptionPane.showMessageDialog(this, "进入用户界面");
					new UserMainView(name).setVisible(true);
					this.dispose();
				} else {
					JOptionPane.showMessageDialog(this, "账号或密码出错");
				}
			} else if (this.jRadioButton2.isSelected()) {
				boolean b = c.login(name, pw, 2);
				if (b) {
					JOptionPane.showMessageDialog(this, "进入商家界面");
					new ShopMainView(name).setVisible(true);
					this.dispose();
				} else {
					JOptionPane.showMessageDialog(this, "账号或密码出错");
				}
			} else if (this.jRadioButton3.isSelected()) {
				boolean b = c.login(name, pw, 3);
				if (b) {
					JOptionPane.showMessageDialog(this, "进入管理员界面");
					new AdminMainView().setVisible(true);
					this.dispose();
				} else {
					JOptionPane.showMessageDialog(this, "no");
				}
			}

		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginView().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JRadioButton jRadioButton3;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}